### ISSUE TITLE
Project status or roadmap?

### ISSUE THREAD

**Issue by sappenin** [novifinancial/fastpay#9]
Hello, this is a very interesting project/idea -- can anyone share any updates around the future of this project/concept, perhaps a roadmap or other information around potential future direction?

**Comment by matbd** [comment]
Thanks for your note. We have actually started looking into several extensions of the FastPay protocol recently (e.g. confidentially and unlinkability). If you're interested in collaborating, feel free to drop an email to Alberto and me. (Our addresses are on the pdf.)
